/**
 * Shared domain constants for the ALSABBAT platform.
 * Kept framework-agnostic so both frontend and tooling can consume them.
 * The backend remains the source of truth (`GET /api/system/meta`).
 */
const BRAND_COLORS = {
  PRIMARY: '#FCCF2B',
  SECONDARY: '#012891',
  TERTIARY: '#222222',
  LIGHT: '#FEFEFE',
};

const ENTITY_STATUS = ['ACTIVE', 'INACTIVE', 'ARCHIVED'];
const TEAM_CATEGORIES = ['FIRST_TEAM', 'RESERVE_TEAM', 'YOUTH_TEAM', 'WOMEN_TEAM', 'ACADEMY', 'OTHER'];
const PLAYER_POSITIONS = ['GOALKEEPER', 'DEFENDER', 'MIDFIELDER', 'FORWARD'];
const PLAYER_STATUS = ['ACTIVE', 'INJURED', 'SUSPENDED', 'ON_LOAN', 'INACTIVE', 'RETIRED'];
const STAFF_ROLES = [
  'HEAD_COACH',
  'ASSISTANT_COACH',
  'GOALKEEPER_COACH',
  'FITNESS_COACH',
  'TEAM_MANAGER',
  'MEDICAL_STAFF',
  'ANALYST',
  'KIT_MANAGER',
  'OTHER',
];
const SEASON_STATUS = ['UPCOMING', 'ACTIVE', 'COMPLETED', 'ARCHIVED'];
const COMPETITION_TYPES = ['LEAGUE', 'CUP', 'TOURNAMENT', 'FRIENDLY'];
const MATCH_STATUS = ['SCHEDULED', 'UPCOMING', 'LIVE', 'FINISHED', 'POSTPONED', 'CANCELLED'];
const MATCH_VENUE_TYPES = ['HOME', 'AWAY', 'NEUTRAL'];
const POST_STATUS = ['DRAFT', 'SCHEDULED', 'PUBLISHED', 'ARCHIVED'];
const MEDIA_TYPES = ['IMAGE', 'VIDEO', 'DOCUMENT'];
const ROLES = [
  'SUPER_ADMIN',
  'CONTENT_ADMIN',
  'GALLERY_ADMIN',
  'SOCIAL_MEDIA_ADMIN',
  'STORE_ADMIN',
  'ORDER_ADMIN',
];

module.exports = {
  BRAND_COLORS,
  ENTITY_STATUS,
  TEAM_CATEGORIES,
  PLAYER_POSITIONS,
  PLAYER_STATUS,
  STAFF_ROLES,
  SEASON_STATUS,
  COMPETITION_TYPES,
  MATCH_STATUS,
  MATCH_VENUE_TYPES,
  POST_STATUS,
  MEDIA_TYPES,
  ROLES,
};
